[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
webrtc = "0.10.1"
tokio = { version = "1.36.0", features = ["full"] }
serde = "1.0.197"
serde_json = "1.0.116"
base64 = "0.22.0"
uuid = "1.3.1"
anyhow = "1.0.82"
reqwest = { version = "0.12.5", features = ["json"] }
